name: Feature request
description: Propose an improvement to stack orchestration or evaluation
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What limitation are you hitting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Risks/Tradeoffs
